---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[drush::default]
    attributes:
  - name: git
    run_list:
      - recipe[git]
      - recipe[drush::default]
    attributes:
      drush:
        install_method: 'git'
        version: 'master'
  - name: git-7
    run_list:
      - recipe[git]
      - recipe[drush::default]
    # These don't have php 5.4 and will fail.
    excludes: ['ubuntu-12.04', 'centos-6.7']
    attributes:
      drush:
        install_method: 'git'
        version: '7.x'
  - name: git-8
    run_list:
      - recipe[git]
      - recipe[drush::default]
    # These don't have php 5.4 and will fail.
    excludes: ['ubuntu-12.04', 'centos-6.7']
    attributes:
      drush:
        install_method: 'git'
        version: '8.x'
  - name: phar-8
    run_list:
      - recipe[git]
      - recipe[drush::default]
    # These don't have php 5.4 and will fail.
    excludes: ['ubuntu-12.04', 'centos-6.7']
    attributes:
      drush:
        install_method: 'phar'
        version: '8.0.0'
